name: projek_akhir_mobile_adit
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  html: ^0.15.4
  flutter_inappwebview: ^6.0.0
  logger: ^2.5.0
  shared_preferences: ^2.0.6
  intl: ^0.18.0
  url_launcher: ^6.3.1
  permission_handler: ^11.0.0
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/anggota2.jpg
    - assets/images/Arif.jpg
    - assets/logos/bg-biru.jpg
    - assets/logos/bg-biru.png
    - assets/logos/bg-putih.jpg
    - assets/logos/bg-putih.png
